### ISSUE TITLE
perf._utils.jitwarmupoptions()?

### ISSUE THREAD

**Issue by Samureus** [haypo/perf#14]
I think that to solve the warmup issue, you may need to add the following options when testing on pypy, e.g.:

`pypy --jit threshold=1,function_threshold=1`

You can find more details by checking the output of `pypy --jit help`, by default the JIT will **only** start working after 1039 loops.

That's why I was suggesting the title of this issue, these command line options would vary by JITted Python implementation, e.g.:

- If I understand correctly under Jython under [Oracle's JDK](https://docs.oracle.com/javase/8/docs/technotes/tools/unix/java.html), the argument might be `jython -J-Xcomp` (you'll see that it takes its sweet time starting compared to a regular jython):

> -Xcomp
Forces compilation of methods on first invocation. By default, the Client VM (-client) performs 1,000 interpreted method invocations and the Server VM (-server) performs 10,000 interpreted method invocations to gather information for efficient compilation. Specifying the -Xcomp option disables interpreted method invocations to increase compilation performance at the expense of efficiency.

- If using Pyston, according to the README at https://github.com/dropbox/pyston, you should try `-O` (you can see it in action with `pyston -O -v`):

> -O
Force Pyston to always run at the highest compilation tier. This doesn't always produce the fastest running time due to the lack of type recording from lower compilation tiers, but similar to -n can help test the code generator.

- If running under IronPython, you probably could try with [`-X:CompilationThreshold 1`](https://github.com/IronLanguages/main/search?utf8=%E2%9C%93&q=X%3ACompilationThreshold)

> -X:CompilationThreshold  The number of iterations before the interpreter starts compiling

**Comment by squeaky-pl** [comment]
About running with `pypy --jit threshold=1,function_threshold=1` this is not a good idea IMHO. Nobody does that in production. It's wasteful. It will cause a lot of tracing and compilation. Probably increase pressure on the garbage collector in some real world benchmarks. Maybe it could win speed in some microbenchmarks. What should be done instead is use default parameter here and warmup the JIT "enough". Not sure how many iterations would be enough though.

**Comment by mattip** [comment]
It seems like the goal of a benchmarking suite is not necessarily to "win" some arbitrary competition, rather as a point of reference in some ongoing process. So IMO all the tricks to get a better score obscure the real goal. Default setups allow developers to tweak the defaults over time, and compare over a wide range of benchmarks how those play out.

Hopefully any microbenchmark will reach a plateau withing a few seconds of startup, I think measuring that plateau should be the goal. (me mumble something about statistical change detection here)

**Comment by haypo** [comment]
@squeaky-pl and @mattip explained the rationale: it's not a good idea :-) I close the issue.

I started to document how to benchmark PyPy (JIT compilers): http://perf.readthedocs.io/en/latest/perf.html#jit-compilers
