### ISSUE TITLE
Mean error of distribution

### ISSUE THREAD

**Issue by serhiy-storchaka** [haypo/perf#20]
Standard deviation doesn't have direct relation to median. It has relation to arithmetic mean. Arithmetic mean is a value that minimize the squared deviation, median is a value that minimize the mean absolute error. https://en.wikipedia.org/wiki/Median#Optimality_property

I think it would be more natural to report the mean absolute error of median rather of standard deviation.

**Comment by haypo** [comment]
See issue #1 for the previous discussion.

**Comment by haypo** [comment]
I don't want to display median and mean, default perf output should remain short. So I understand that there are two choices:

* display median with MAD (replace std dev with MAD)
* display mean with standard deviation

**Comment by haypo** [comment]
The commit 75969e7cddbaeef3e2e4522251e65d371f2b455c replaced "Median +- std dev" with "Median +- MAD" and added median_abs_dev(), mean() and stdev() to Benchmark.

Before, I didn't want to add a stdev() method to Benchmark because I wasn't sure if it should be centered on mean or median. Now it's just a cached statistics.stdev(bench.get_samples()).

**Comment by haypo** [comment]
Ok, let's take a very dummy microbenchmark, bench.py:

```
import perf
runner = perf.Runner(warmups=2, samples=4)
runner.timeit('bool(True)', 'bool(True)', duplicate=4096)
```

Results on my laptop without tuning the system for benchmarks. As expected, the result is very unstable:

```
haypo@selma$ ./python -m perf show --hist --stats bench.json.gz 

234 ns:   3 ##
264 ns: 114 ###############################################################################
293 ns:   9 ######
322 ns:   2 #
351 ns:   0 |
381 ns:   0 |
410 ns:   0 |
439 ns:   1 #
469 ns:   0 |
498 ns:   1 #
527 ns:   1 #
557 ns:   0 |
586 ns:   1 #
615 ns:   1 #
644 ns:   1 #
674 ns:   2 #
703 ns:   1 #
732 ns:   1 #
762 ns:   2 #
791 ns:  15 ##########
820 ns:   5 ###

Total duration: 1 min 14.5 sec
Start date: 2017-03-06 23:30:49
End date: 2017-03-06 23:33:11
Raw sample minimum: 137 ms
Raw sample maximum: 444 ms

Number of runs: 42
Total number of samples: 160
Number of samples per run: 4
Number of warmups per run: 2
Loop iterations per sample: 2^19 (128 outer-loops x 4096 inner-loops)

Minimum: 262 ns (-5%)
Median +- MAD: 276 ns +- 10 ns
Mean +- std dev: 371 ns +- 196 ns
Maximum: 847 ns (+207%)

ERROR: the benchmark is very unstable, the standard deviation is very high (stdev/mean: 53%)!
Try to rerun the benchmark with more runs, samples and/or loops

Median +- MAD: 276 ns +- 10 ns
```

Median and MAD do their job of "hiding" outliers. The question is if displaying median with MAD gives more reproductible benchmark results than displaying mean with std dev?

**Comment by haypo** [comment]
perf 1.0 now displays "Mean +- std dev". I wrote notes about Minimum, Mean, Median, etc. in perf documentation:
http://perf.readthedocs.io/en/latest/analyze.html#statistics
