### ISSUE TITLE
Can I use this project as a library?

### ISSUE THREAD

**Issue by guyskk** [haypo/perf#21]
I want to use the timeit function in this project to replace standard timeit, and read the document and source code but didn't found a proper way to do it.

Accurately, I want to analyze the raw benchmark result(the time series of run timeit). I found this project  deal with CPU affinity and CPU isolated, it's result probably more stable than standard timeit.

Here is a picture of the time series of run timeit:
![benchmark_raw](https://cloud.githubusercontent.com/assets/6367792/23545414/3d0f67f0-0036-11e7-8ab9-2b0c4a8f9789.png)
\>50% data is noise.

My stable benchmark algorithm: https://github.com/guyskk/validr/blob/cython/benchmark/stable_timeit.py
see also: https://github.com/guyskk/validr/issues/9

**Comment by haypo** [comment]
Are you looking for Runner.timeit() method?
http://perf.readthedocs.io/en/latest/api.html#Runner.timeit

Documentation explaining how to run stable benchmarks:
http://perf.readthedocs.io/en/latest/perf.html#stable-and-reliable-benchmarks

In short: run "sudo python3 -m perf system tune" :-)

**Comment by haypo** [comment]
> My stable benchmark algorithm: https://github.com/guyskk/validr/blob/cython/benchmark/stable_timeit.py

You code runs a benchmark only using a single process, don't calibrate the benchmark (compute automatically the number of outer loops), don't compute a warmup sample, and only compute 3 samples.

perf uses 1 process to calibrate the benchmark, 20 processes to run the benchmark. Each process runs the benchmark a first time to warmup the process, then compute 3 samples. Total: 60 samples, much better than only 3 samples, to get a better statistical distribution.

Well, please test perf and come back to me :-)

**Comment by guyskk** [comment]
Yes, there much more noise in my benchmark, and I only choose 3 points in my 3 samples, but this approach can get almost the same stability result as perf. 
So I want to use perf to get less noise raw data, analyze them, and get a more stable result.

**Comment by haypo** [comment]
By the way, you can run a benchmark multiple times to collect more samples and then enhance the distribution:

```
python3 script.py --append bench.json
python3 script.py --append bench.json
python3 script.py --append bench.json
```

Maybe even reboot between runs to ensure that results are reproductible. Then analyze results using dump, stats and hist.

You can also use --append with "python3 -m perf timeit".

**Comment by guyskk** [comment]
@haypo I failed to run `perf system tune` in docker container `python:3` which is based on `debian:8`:
```
root@cd5e29bc20d2:/io# python -m perf system tune
Tune the system configuration to run benchmarks

Failed to get D-Bus connection: Unknown error -1
irqbalance: unrecognized service
Failed to get D-Bus connection: Unknown error -1
irqbalance: unrecognized service
System state
============

Perf event: Maximum sample rate: 100000 per second
ASLR: Full randomization
Linux scheduler: No CPU is isolated
IRQ affinity: Default IRQ affinity: CPU 0-1
IRQ affinity: IRQ affinity: IRQ 0-15,24-37=CPU 0-1

Advices
=======

Linux scheduler: Use isolcpus=<cpu list> kernel parameter to isolate CPUs
Linux scheduler: Use rcu_nocbs=<cpu list> kernel parameter (with isolcpus) to not schedule RCU on isolated CPUs

Errors
======

Perf event: Failed to write into /proc/sys/kernel/perf_event_max_sample_rate: [Errno 30] Read-only file system: '/proc/sys/kernel/perf_event_max_sample_rate'
Turbo Boost (MSR): Failed to read MSR 0x1a0 from /dev/cpu/0/msr: [Errno 2] No such file or directory: '/dev/cpu/0/msr'
Turbo Boost (MSR): Try to load the msr kernel module: sudo modprobe msr
root@cd5e29bc20d2:/io# sudo modprobe msr
bash: sudo: command not found
```
It also not works in MacOSX. 
Does it depend on some special Linux features?

**Comment by haypo** [comment]
Oh, I didn't try to run benchmarks on a VM or a container. I'l not
surprised that system doesn't work. Maybe you should run perf system tune
on the host?

**Comment by haypo** [comment]
"It also not works in MacOSX. Does it depend on some special Linux features?"

Yes, I wrote the system feature for Linux. I didn't try other platforms.

**Comment by haypo** [comment]
I made changes in the system commands: "system show" should no more fail on macOS. In fact, the command now only displays:

```
WARNING: no operation available for your platform
```

It doesn't seem to be as easy as Linux to implement operations to show/tune the system for benchmarks. For example, it seems like writing kernel module is required to read/modify the Turbo Boost CPU MSR!

For containers (docker), you will probably still get errors like "Perf event: Failed to write into /proc/sys/kernel/perf_event_max_sample_rate: [Errno 30] Read-only file system: '/proc/sys/kernel/perf_event_max_sample_rate'". I don't know how to handle containers.

I consider that the initial issue is fixed, so I close the issue.
