### ISSUE TITLE
LOTS of output

### ISSUE THREAD

**Issue by wm75** [haypo/perf#23]
I just started using perf again after a while and I'm suddenly getting flooded with output that I don't remember seeing before. Just running python3 -m perf timeit "int('3')" or, in fact, any command after timeit gives 100s of lines of output of the sort:
.....................
(2.081039619447611e-07, 2.0966166496341754e-07, 2.0834495735241876e-07, 2.0798590087862945e-07, 2.0800072097690303e-07, 2.095399551389071e-07, 2.0929106521461183e-07, 2.0892218017577735e-07, 2.0930357360823826e-07, 2.0832581901567004e-07, 2.0800754356280204e-07, 2.0977499198826521e-07, 2.091219863890187e-07, 2.0929869270353008e-07, 2.0946509552040304e-07, 2.0924766921948112e-07, 2.0950784873977057e-07, 2.0922689056464272e-07, 2.0953447914077994e-07, 2.1273634529146712e-07, 2.138244304655118e-07, 2.2082462883092624e-07, 2.1117857170079024e-07, 2.4641811561566807e-07, 2.0901058578499943e-07, 2.0829808425847085e-07, 2.1190711975080379e-07, 2.0787903594852997e-07, 2.0788304519632483e-07, 2.1075399589572108e-07, 2.0771297073313155e-07, 2.0974149704013068e-07, 2.0810379028346482e-07, 2.1122927856484508e-07, 2.1184817314279236e-07, 2.113853111267161e-07, 2.103219852445104e-07, 2.0893610191280443e-07, 2.0859032440201375e-07, 2.0787958335787005e-07, 2.0793043708881853e-07, 2.0974521255413825e-07, 2.099091072071957e-07, 2.0979626083432457e-07, 2.1052976417572367e-07, 2.575373821249449e-07, 2.0835235405025632e-07, 2.1008222007672106e-07, 2.4275443840163224e-07, 2.095295696270122e-07, 2.411018028263684e-07, 2.093657970429763e-07, 2.0874368476982152e-07, 2.1040027618421386e-07, 2.3591923522907343e-07, 2.1126461601309043e-07, 2.1081210899512315e-07, 2.1505261421292388e-07, 2.1558845520082415e-07, 2.157484321595876e-07) 60
{<class 'int'>} 0
{144115188075855872: 29990941615, 1: 0}
{144115188075855872: 29990941615, 1: 0, 288230376151711744: 60430860557}
{144115188075855872: 29990941615, 1: 0, 288230376151711744: 120482205984}
{144115188075855872: 29990941615, 1: 0, 288230376151711744: 120482205984, 576460752303423488: 119895708889}
{144115188075855872: 29990941615, 1: 0, 288230376151711744: 180434332031, 576460752303423488: 119895708889}
{144115188075855872: 29990941615, 1: 0, 288230376151711744: 180434332031, 576460752303423488: 240687269066}
{144115188075855872: 29990941615, 1: 0, 72057594037927936: 15081010613, 288230376151711744: 180434332031, 576460752303423488: 240687269066}
{144115188075855872: 29990941615, 1: 0, 72057594037927936: 15081010613, 288230376151711744: 180434332031, 576460752303423488: 361122706223}
{144115188075855872: 29990941615, 1: 0, 72057594037927936: 15081010613, 288230376151711744: 240761979782, 576460752303423488: 361122706223}
{144115188075855872: 29990941615, 1: 0, 72057594037927936: 15081010613, 288230376151711744: 300807808959, 576460752303423488: 361122706223}
{144115188075855872: 29990941615, 1: 0, 72057594037927936: 15081010613, 288230376151711744: 300807808959, 576460752303423488: 481030891270}
{144115188075855872: 29990941615, 1: 0, 72057594037927936: 15081010613, 576460752303423488: 481030891270, 18014398509481984: 3778970303, 288230376151711744: 300807808959}
{144115188075855872: 29990941615, 1: 0, 72057594037927936: 15081010613, 576460752303423488: 601581508867, 18014398509481984: 3778970303, 288230376151711744: 300807808959}
{144115188075855872: 60154062078, 1: 0, 72057594037927936: 15081010613, 576460752303423488: 601581508867, 18014398509481984: 3778970303, 288230376151711744: 300807808959}
{144115188075855872: 60154062078, 1: 0, 72057594037927936: 15081010613, 576460752303423488: 722329915412, 18014398509481984: 3778970303, 288230376151711744: 300807808959}
{144115188075855872: 60154062078, 1: 0, 36028797018963968: 7538941801, 72057594037927936: 15081010613, 576460752303423488: 722329915412, 18014398509481984: 3778970303, 288230376151711744: 300807808959}
{144115188075855872: 60154062078, 1: 0, 36028797018963968: 7538941801, 72057594037927936: 15081010613, 576460752303423488: 722329915412, 18014398509481984: 3778970303, 288230376151711744: 361194335008}
{144115188075855872: 60154062078, 1: 0, 36028797018963968: 7538941801, 72057594037927936: 15081010613, 576460752303423488: 842941006149, 18014398509481984: 3778970303, 288230376151711744: 361194335008}
{144115188075855872: 60154062078, 1: 0, 36028797018963968: 7538941801, 72057594037927936: 15081010613, 576460752303423488: 963729409628, 18014398509481984: 3778970303, 288230376151711744: 361194335008}

Not sure what I'm doing wrong that I didn't do before.

**Comment by wm75** [comment]
Ok, this is quite embarassing and I'm sorry for bringing this up. I just found out that this output only occurs when I'm running perf from my ~ folder and finally realized that there is an old debug version of statistics.py in there into which I've inserted prints that are generating this. So, effectively, I have been shadowing the stdlib statistics module and created bogus myself.
Sorry again.

**Comment by haypo** [comment]
No problem :-) It's nice to see that perf has users ;-)
