### ISSUE TITLE
PerfEP: More examples in the README

### ISSUE THREAD

**Issue by moreati** [haypo/perf#24]
A Perf Enhancement Proposal: I stumbled across your project on the recommendation of  `pypy -mtimeit ...`. Viewing the README on PyPI left me a bit underwhelmed about trying it out. The bullets list of features is a bit dry.

Would you be interested in a PR with a new README? One written form the perspective of a new user. Naturally you would have final approval, and if you decided not to use it I would not be offended.

I wanted to run the idea by you first, before submitting something out the blue.

**Comment by haypo** [comment]
I am trying put all documentation in doc/.
Did you reach this section?

https://perf.readthedocs.io/en/latest/examples.html

Yes, I am interested by doc enhancements!

**Comment by moreati** [comment]
> I am trying put all documentation in doc/.

A noble goal. I'm not  proposing to make the README any longer.

> Did you reach this section?

Eventually. However, I think a few strategically chosen examples deserve more prominence - in order to whet prospective user's appetite, and to *show* answers to the questions

- What can I do with this?
- How do I do it?

**Comment by moreati** [comment]
https://github.com/moreati/perf/blob/9b1dbb679113f51057299402a1e48a5d94533504/README.rst is the sort of thing I had in mind

**Comment by haypo** [comment]
> https://github.com/moreati/perf/blob/9b1dbb679113f51057299402a1e48a5d94533504/README.rst is the sort of thing I had in mind

Ok, I see. I like the global shape, but I have remarks. Please create PR, so I can comment it ;-)

**Comment by haypo** [comment]
Ok, I picked your README in commit e340733bfb571727bf1b2e2bb834e1f87401a5dd, thanks!
