### ISSUE TITLE
Max time is not used/implemented

### ISSUE THREAD

**Issue by gagoman** [haypo/perf#32]
Good day.

As far as I can see `max_time` of `Runner` is not used.
First I was going to implement it but I've found out that there is also a commit da7ede7f11ea70a70131dfb15436d2be9358f1e8 which notes attribute as removed.

Are there any plans for that?

Best regards.

**Comment by haypo** [comment]
Oh, right, the max_time parameter of Runner constructor is unused. I would prefer to simply remove it. Maybe we need to start to deprecate changes. Maybe for this specific parameter, it's not worth it.

**Comment by gagoman** [comment]
So, should I make a PR to remove it?

**Comment by haypo** [comment]
> So, should I make a PR to remove it?

Yes, that would be great :-)
