### ISSUE TITLE
Benchmark parameters

### ISSUE THREAD

**Issue by gagoman** [haypo/perf#36]
Good day.

This is more a question, than an issue.

So, let's say I want to benchmark multiple implementations (e.g. https://github.com/gagoman/atomicl/blob/master/benchmarks.py). Is a custom cli option is a best way not to duplicate code or make for loops? For example:

```sh
python -m perf benchmarks.py --impl atomicl._py
```

Should we have something like benchmark parameters and benchmark context?

```
perf.Runner(params=dict(impl=[first, second, third]))
```

and benchmark itself:

```
def bench(ctx):
    ctx.impl().do()
```

In case if there are multiple params, context would hold all the permutations.

The idea is stolen from [JMH](http://hg.openjdk.java.net/code-tools/jmh/file/1ddf31f810a3/jmh-samples/src/main/java/org/openjdk/jmh/samples/JMHSample_27_Params.java). If you would like the idea, I can try to describe it more clearly and implement it.

**Comment by haypo** [comment]
Oh right, the documentation should give a short example how to add a command line option.

See this example:
https://github.com/python/performance/blob/master/performance/benchmarks/bm_logging.py#L125


* Important option: add_cmdline_args parameter of perf.Runner()
* runner.argparser gives access to the command line parser
* runner.parse_args() gives command line options

**Comment by gagoman** [comment]
Cool, thank you a lot, will use that.

What do you think about benchmark parametrization? Not pythonic?

**Comment by haypo** [comment]
> What do you think about benchmark parametrization? Not pythonic?

What do you mean? Adding command line arguments to a "benchmarks.py" script?

You are free to use my perf module as you want. I don't see why command line options would be "unpythonic"!?

**Comment by gagoman** [comment]
I'm sorry for a bad explanation. I've asked 2 questions in 1 issue.

I've already got an answer for the first one. Thank you a lot.

I mean adding `context` to `perf.Runner` to have something like:

```
perf.Runner(context=dict(impl=[first, second, third], arg=[1, 2, 3]))
```

and then benchmark like this:

```
def bench(ctx):
    ctx.impl().do(ctx.arg)
```

and is reported like this:

```
(context: impl=first, arg=1) bench: Mean +- std dev: 15.4 ns +- 0.4 ns
(context: impl=second, arg=1) bench: Mean +- std dev: 10.3 ns +- 0.4 ns
...
(context: impl=first, arg=3) bench: Mean +- std dev: 12.3 ns +- 0.3 ns
```

**Comment by haypo** [comment]
```
(context: impl=first, arg=1) bench: Mean +- std dev: 15.4 ns +- 0.4 ns
(context: impl=second, arg=1) bench: Mean +- std dev: 10.3 ns +- 0.4 ns
```

If you put it in the benchmark name, it's fine.

> perf.Runner(context=dict(impl=[first, second, third], arg=[1, 2, 3]))

I think you can do it manually using something like:

```
for func, arg in zip([first, second, third], [1, 2, 3]):
  runner.bench_func("bench[arg=%r]" % arg, func, arg)
```

Maybe write your own helper on top of Runner?

Runner is a complex API. There are many functions to run benchmarks. You can run multple different benchmarks. It spawn child processes, etc.

While your idea is doable, I don't think that it plays well with the current Runner API and architecture.

**Comment by gagoman** [comment]
Ok, got it.

Thank you a lot.
