### ISSUE TITLE
perf.timeit: histogram output

### ISSUE THREAD

**Issue by Tinche** [haypo/perf#5]
It might be useful (and fancy :) to add a flag to perf.timeit to make it output a histogram in addition to the median and stddev.

I know --json-file can be used to get this, but doing it that way includes extra steps and is clunky. The UX would be better if users could just ask for the histogram in one command.

If it was up to me, I'd display the histogram by default in perf.timeit.

**Comment by haypo** [comment]
It was planned, it's now implemented. Enjoy!

**Comment by Tinche** [comment]
Awesome, thanks!
